### get
GET http://localhost:8080/notices
Accept: application/json

###
GET http://localhost:8080/contact
Accept: application/json

###
GET http://localhost:8080/welcome
Accept: application/json

### authenticated
GET http://localhost:8080/myAccount
Accept: application/json
Authorization: Basic tanver@gmail.com 12345

### authenticated
GET http://localhost:8080/myBalance
Accept: application/json
Authorization: Basic tanver@gmail.com 12345

### authenticated
GET http://localhost:8080/myCards
Accept: application/json
Authorization: Basic tanver@gmail.com 12345

### authenticated
GET http://localhost:8080/myLoans
Accept: application/json
Authorization: Basic tanver@gmail.com 12345

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "email": "tanver@gmail.com",
  "password": "12345",
  "role": "ADMIN"
}